server.R, ui.R
=> Organize all metadata and definitions in alphabetical order

server.R, ui.R, utils.R
=> Add search bar to Definiciones y Metadatos

ui.R
=> Rename Acerca del Dashboard tab to Acerca

ui.R
=> Add new author tag to About section

utils.R
=> Add padding beneath the main panel

ui.R
=> Add padding beneath the main panel (in ui.R)

.gitattributes, utils.R
=> Added spacing in-between x-axis bars

utils.R
=> Added border to graphs

server.R, ui.R
This branch closes #48 #49 #50
=> Modify Contacto tab layout

server.R, ui.R, utils.R
This branch closes #10 , #21 and #46
=> Create create_empty_plot_with_message() helper function and modify renderBarPlot()

server.R, ui.R, utils.R
=> added Fuentes and data tables to the sidebar

rsconnect/shinyapps.io/proyectosestadisticosiepr/ViolenciaGeneroPR.dcf, server.R, utils.R
=> modify padding of data tables on sidebar

rsconnect/shinyapps.io/proyectosestadisticosiepr/ViolenciaGeneroPR.dcf, server.R, ui.R, utils.R
=> add titles to data tables and delete data tables from mainpanels

global.R, server.R, ui.R, utils.R
=> Modify renderLinePlot() helper function and delete old text with fuentes

server.R, utils.R
=> modify html inside renderDataTable_Definitions()

rsconnect/shinyapps.io/proyectosestadisticosiepr/ViolenciaGeneroPR.dcf, ui.R, utils.R
Modify padding of buttons on sidebar, change background color and modify title in button in "Definiciones y Metadatos"
=> Modify padding of buttons on sidebar, change background color and modify title in button in "Definiciones y Metadatos"

server.R, ui.R
=> Issue 7 titles

ui.R
Added padding to the PARE logo and change the color of the header from "pink" to "#8dc143" in the ui.R file.
=> Added padding to the PARE logo and changed the colour of the header

server.R, utils.R
Modified the CSV and Excel buttons to download all the data selected by the user. Also, modified the renderDT() function on the server file so its argument **server** receives as parameter **FALSE.** That way all data is sent to the client side (the browser).
=> Modified the CSV and Excel buttons to download all the selected data

server.R, utils.R
Created a function to changed the padding of Y for the legends in the graphs that use facets.
=> Changed the padding on Y for the legends

server.R, ui.R, utils.R
- Moved the legend on top of the graph. 
- Crated a function to calculate the y axis for the graphs with facets depending on the numbers of rows.
- Now graphs bar plots with facets are handled by renderBarPlot_facets.
- Separated the title from the graphs that had facets.
Still the legend of the graph "Movimiento Anual de Casos de Violencia Doméstica en el Tribunal según Ley 54" **is not** presented in **multiple columns**.
=> Moved legends top of graphs

server.R
In Tab: Administración de Tribunales 
For the graph "Movimiento Anual de Casos de Violencia Domestica" changed the text size so the legend would appear in columns.
=> Modified legend so it would be divided into columns

server.R, ui.R, utils.R
- Separated the titles from the maps.
- Fixed an issue with the graph "Incidencia de Violencia Doméstica por Edad de la Víctima" where the height wasn't being send properly.
=> Separated the titles from the maps

utils.R
Changed legend title position:
- Moved title to the top-left.
=> Changes legend title position

server.R, ui.R
Added part of the requested modifications to the text presented.
=> Added part of the requested modifications

utils.R
Changed scaling:
- Using breaks for the x labels.
=> Changed legend scaling

server.R, ui.R
Verified the text of each tab.
=> Verified text

ui.R, utils.R
- Modified the date at the Note in "Negociado de la Policia"
- Modified the function createDropdownCheckbox_añoFiscal() for the tab "Administracion Tribunales"
=> Changed Note in policia  and the years to select in Tribunales

ui.R
Modified natural year from the note.
=> Modified note Negociado Policia
